import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import {
  SidebarProvider,
  Sidebar,
  SidebarContent,
  SidebarTrigger,
  SidebarGroup,
  SidebarGroupLabel,
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuButton,
  SidebarSeparator,
  SidebarInset,
} from "@/components/ui/sidebar";
import Link from "next/link";
import { WorkspaceTools } from "@/components/WorkspaceTools";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const routes = [
  { label: "Workspace", href: "/" },
  { label: "Saved Queries", href: "/saved" },
  { label: "Import / Export", href: "/import" },
  { label: "Playground", href: "/playground" },
  { label: "Schema", href: "/schema" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="min-h-full flex">
        <SidebarProvider>
          <div className="flex w-full min-h-screen">
            <Sidebar>
              <SidebarContent>
                <SidebarGroup>
                  <SidebarGroupLabel>Navigation</SidebarGroupLabel>

                  <SidebarMenu>
                    {routes.map((route) => (
                      <SidebarMenuItem key={route.href}>
                        <SidebarMenuButton asChild>
                          <Link href={route.href}>{route.label}</Link>
                        </SidebarMenuButton>
                      </SidebarMenuItem>
                    ))}
                  </SidebarMenu>
                </SidebarGroup>

                <SidebarSeparator />

                <SidebarGroup>
                  <SidebarGroupLabel>Workspace Tools</SidebarGroupLabel>
                  <WorkspaceTools />
                </SidebarGroup>
              </SidebarContent>
            </Sidebar>

            <SidebarInset>
              <SidebarTrigger />
              {children}
            </SidebarInset>
          </div>
        </SidebarProvider>

        <Toaster richColors />
      </body>
    </html>
  );
}
